-- 코드를 입력하세요
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.TOTAL_SALES
FROM (SELECT B.BOOK_ID, B.AUTHOR_ID, B.CATEGORY, SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
    FROM BOOK AS B
    JOIN BOOK_SALES AS BS
    ON (B.BOOK_ID = BS.BOOK_ID AND BS.SALES_DATE LIKE '2022-01%')
    GROUP BY B.AUTHOR_ID, B.CATEGORY
    ORDER BY B.AUTHOR_ID, B.CATEGORY DESC) AS B
JOIN AUTHOR AS A
ON B.AUTHOR_ID = A.AUTHOR_ID


