-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.NAME
FROM (SELECT AI.ANIMAL_ID, AI.NAME, TIMESTAMPDIFF(SECOND, AI.DATETIME,AO.DATETIME) AS TIME
FROM ANIMAL_INS AS AI
JOIN ANIMAL_OUTS AS AO
ON AI.ANIMAL_ID = AO.ANIMAL_ID) AS A
ORDER BY A.TIME DESC
LIMIT 2
