SELECT DISTINCT CAR.CAR_ID, CAR.CAR_TYPE, FLOOR(CAR.DAILY_FEE*(1 - (SUBSTRING_INDEX(PLAN.DISCOUNT_RATE, '%', 1))*0.01)*30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CAR
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY ON CAR.CAR_ID = HISTORY.CAR_ID
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN ON PLAN.CAR_TYPE = CAR.CAR_TYPE
WHERE CAR.CAR_TYPE IN ('세단', 'SUV')
AND CAR.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE <= '2022-11-01' AND END_DATE >= '2022-11-01')
AND PLAN.DURATION_TYPE = '30일 이상'
HAVING FEE BETWEEN 500000 AND 2000000-1
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;