--Create table CUSTOMER (
--	cno number(9) not null,
--	name varChar2(15) not null,
--	passed varChar2(20) not null,
--	email varChar2(20) not null,
--	constraint PK_customer primary key (cno)
--);
--
--Create table EBOOK (
--	isbn varchar2(10) not null,
--	c_cno number(9) not null,
--	title varchar2(20) not null,
--	publisher varchar2(10),
--	year number(4),
--	extTimes number(1),
--	e_dateRented date,
--	e_dateDue date,
--	constraint PK_ebook primary key (isbn),
--	constraint FK_customer FOREIGN KEY (c_cno) 
--    REFERENCES CUSTOMER(cno)
--  constraint checkExtime check (exttimes <4)
--);
--
--Create table AUTHORS (
--	author varchar2(15) not null,
--	e_isbn varchar2(10) not null,
--	constraint PK_authors primary key (author),
--	constraint FK_ebook foreign key (e_isbn)
--	references EBOOK(isbn)
--);
--
--Create table RESERVE(
--	e_isbn varchar2(10) not null,
--	c_cno number(9) not null,
--	dateTime date not null,
--	constraint FK_ebook foreign key(e_isbn)
--	references EBOOK(isbn),
--	constraint FK_customer foreign key(c_cno)
--	references CUSTOMER(cno)
--);
--
--Create table PREVIOUSRENTAL(
--	e_isbn varchar2(10) not null,
--	pr_dateRented date not null,
--	pr_dateReturned date not null,
--	c_cno number(9) not null,
--	constraint PK_previousRental primary key (e_isbn, pr_dateRented),
--	constraint FK_ebook foreign key(e_isbn)
--	references EBOOK(isbn),
--	constraint FK_customer foreign key(c_cno)
--	references CUSTOMER(cno)
--);

--create view Resinfo as
--    (select e.sibn, e.title, c.cno, c.name, c.email, r.datetime
--    from ebook e, customer c, reserve r
--    where e.c_cno = c.cno
--    and e.isbn = r.e_isbn
--    );
--describe Resinfo
