--insert into emp
--values(7370,'AlEX','MANAGER',7839,SYSDATE,2900,null,10,null);
--savepoint udEN1;
--
--update emp
--set sal = sal + 50
--where ename = 'AlEX';
--
--delete from emp
--where ename = 'AlEX';
--
--rollback to udEN1;
--rollback;
--select * from emp

--select * from ALL_users;    -- 계정 확인

--conn SYSTEM/11191001;
--create user C##tester identified by 1234;
----grant create session to C##tester;
--conn C##tester/1234;
--show user;
--create table ex1(
--name varchar2(4)
--);
--describe ex1

--conn SYSTEM/11191001;
--grant create user to C##TESTER;
--grant create session to C##TESTER;
--grant create table to C##TESTER;
--alter user C##TESTER default tablespace users quota unlimited on users;

--conn C##TESTER/1234
--create table test2(
--name varchar2(4) not null
--);
--commit;
--insert into test2(name)
--values ('ALEX');
--select * from test2;