-- 코드를 입력하세요
SELECT FD.PRODUCT_ID, FD.PRODUCT_NAME, (FO.AMOUNT * FD.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT AS FD
JOIN (SELECT PRODUCT_ID, COUNT(*) AS CNT, SUM(AMOUNT) AS AMOUNT
      FROM FOOD_ORDER
      WHERE PRODUCE_DATE LIKE '2022-05%'
      GROUP BY PRODUCT_ID) AS FO
ON FD.PRODUCT_ID = FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FD.PRODUCT_ID

