-- 코드를 입력하세요
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, left(R.CREATED_DATE,10) as CREATED_DATE
FROM USED_GOODS_REPLY as R, USED_GOODS_BOARD as B
WHERE B.CREATED_DATE like '2022-10%'
and B.BOARD_ID = R.BOARD_ID
ORDER BY R.CREATED_DATE asc, B.TITLE asc