-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT AS P, DOCTOR AS D, APPOINTMENT AS A
WHERE A.APNT_CNCL_YN = 'N'
AND A.MCDP_CD = 'CS'
AND D.DR_ID = A.MDDR_ID
AND P.PT_NO = A.PT_NO
AND A.APNT_YMD like '2022-04-13%'
ORDER BY A.APNT_YMD