WITH RECURSIVE HOURS AS (
    SELECT 0 AS NUM 
    UNION ALL
    SELECT NUM+1 FROM HOURS
    WHERE NUM < 23
)

SELECT H.NUM AS HOUR, COUNT(AO.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS AS AO
RIGHT JOIN HOURS AS H
ON H.NUM = HOUR(AO.DATETIME)
GROUP BY HOUR
ORDER BY HOUR


