-- 코드를 입력하세요
SELECT UG.WRITER_ID, UU.NICKNAME, UG.TOTAL_SALES
FROM (SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING TOTAL_SALES >= 700000) AS UG
JOIN USED_GOODS_USER AS UU
ON UG.WRITER_ID = UU.USER_ID
ORDER BY UG.TOTAL_SALES