-- 코드를 입력하세요
SELECT C.MONTH, C.CAR_ID, SUM(C.COUNT) AS RECORDS
FROM (SELECT CAR_ID, MONTH(START_DATE) AS MONTH, COUNT(*) AS COUNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN DATE('2022-08-01') AND DATE('2022-10-31')
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5) AS C
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC

# SELECT CAR_ID, MONTH(START_DATE) AS MONTH, COUNT(*) AS COUNT
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE START_DATE BETWEEN DATE('2022-08-01') AND DATE('2022-10-31')
#     GROUP BY CAR_ID
#     HAVING COUNT(*) >= 5
