-- 코드를 입력하세요
SELECT DISTINCT(CRCC.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS CRCC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCR
ON (CRCC.CAR_TYPE = '세단' 
    AND CRCC.CAR_ID = CRCR.CAR_ID
    AND CRCR.START_DATE LIKE '2022-10%')
ORDER BY CRCC.CAR_ID DESC
