-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK AS B,
(SELECT BOOK_ID, SALES
 FROM BOOK_SALES
 WHERE SALES_DATE like '2022-01%') AS BS
WHERE B.BOOK_ID = BS.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY