-- 코드를 입력하세요
SELECT FP.CATEGORY, FP.PRICE AS MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT AS FP, 
    (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    HAVING CATEGORY IN ('과자','국','김치','식용유')) AS FM
WHERE FP.CATEGORY = FM.CATEGORY
AND FP.PRICE = FM.MAX_PRICE
ORDER BY FM.MAX_PRICE DESC

