-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, left(DATE_OF_BIRTH,10) as DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL
AND DATE_OF_BIRTH like '%-03-%'
AND GENDER = 'W'
ORDER BY MEMBER_ID asc